# Configuración de la base de datos
spring.datasource.url=jdbc:mariadb://192.168.109.31:3306/peliculas
spring.datasource.username=sergio
spring.datasource.password=abc123.
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Puerto del servidor
server.port=9001